#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Mon Apr 22 19:51:42 2013

import wx

# begin wxGlade: extracode
# end wxGlade



class CarritoFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CarritoFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self.panel_1, -1, "CARRITO")
        self.list_ctrl_1 = wx.ListCtrl(self.panel_1, -1, style=wx.LC_REPORT|wx.LC_AUTOARRANGE|wx.SUNKEN_BORDER)
        self.label_6 = wx.StaticText(self.panel_1, -1, "TOTAL: $349")
        self.button_1 = wx.Button(self.panel_1, -1, "Quitar")
        self.static_line_1 = wx.StaticLine(self.panel_1, -1)
        self.radio_box_1 = wx.RadioBox(self.panel_1, -1, "Tipo de Compra", choices=["Casual", "Cliente"], majorDimension=1, style=wx.RA_SPECIFY_ROWS)
        self.panel_compra_cliente = wx.Panel(self.panel_1, -1)
        self.label_2 = wx.StaticText(self.panel_compra_cliente, -1, "Buscar:")
        self.text_ctrl_4 = wx.TextCtrl(self.panel_compra_cliente, -1, "")
        self.radio_btn_1 = wx.RadioButton(self.panel_compra_cliente, -1, "Nombre")
        self.radio_btn_2 = wx.RadioButton(self.panel_compra_cliente, -1, "DNI")
        self.list_ctrl_2 = wx.ListCtrl(self.panel_compra_cliente, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.checkbox_1 = wx.CheckBox(self.panel_compra_cliente, -1, "Condicional")
        self.static_line_2 = wx.StaticLine(self.panel_1, -1)
        self.label_3 = wx.StaticText(self.panel_1, -1, "Entrega: ")
        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, -1, "")
        self.label_4 = wx.StaticText(self.panel_1, -1, "Paga con:")
        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, -1, "")
        self.label_5 = wx.StaticText(self.panel_1, -1, "Vuelto:")
        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, -1, "", style=wx.TE_READONLY)
        self.static_line_3 = wx.StaticLine(self.panel_1, -1)
        self.button_3 = wx.Button(self.panel_1, -1, "Im&primir")
        self.button_4 = wx.Button(self.panel_1, -1, "&Cancelar")
        self.button_5 = wx.Button(self.panel_1, -1, "&Aceptar")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CarritoFrame.__set_properties
        self.SetTitle("Carrito de Compras")
        self.label_1.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_6.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.radio_box_1.SetMinSize((200, 46))
        self.radio_box_1.SetSelection(0)
        self.text_ctrl_4.SetMinSize((200, 21))
        self.panel_compra_cliente.Enable(False)
        self.label_3.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_1.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_4.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_2.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_5.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.text_ctrl_3.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CarritoFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.label_1, 0, wx.ALL|wx.ADJUST_MINSIZE, 10)
        sizer_7.Add(self.list_ctrl_1, 1, wx.ALL|wx.EXPAND, 5)
        sizer_7.Add(self.label_6, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 10)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.static_line_1, 0, wx.BOTTOM|wx.EXPAND, 10)
        sizer_2.Add(self.radio_box_1, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ADJUST_MINSIZE, 10)
        sizer_10.Add(self.label_2, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 20)
        sizer_10.Add(self.text_ctrl_4, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 20)
        sizer_10.Add(self.radio_btn_1, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.radio_btn_2, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 20)
        sizer_9.Add(sizer_10, 0, wx.ALL|wx.EXPAND, 5)
        sizer_9.Add(self.list_ctrl_2, 1, wx.EXPAND, 0)
        sizer_9.Add(self.checkbox_1, 0, wx.TOP|wx.ADJUST_MINSIZE, 10)
        self.panel_compra_cliente.SetSizer(sizer_9)
        sizer_2.Add(self.panel_compra_cliente, 1, wx.ALL|wx.EXPAND, 5)
        sizer_2.Add(self.static_line_2, 0, wx.TOP|wx.EXPAND, 10)
        sizer_6.Add(self.label_3, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6.Add(self.text_ctrl_1, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 40)
        sizer_6.Add(self.label_4, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6.Add(self.text_ctrl_2, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 40)
        sizer_6.Add(self.label_5, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 10)
        sizer_6.Add(self.text_ctrl_3, 0, wx.RIGHT|wx.ADJUST_MINSIZE, 10)
        sizer_2.Add(sizer_6, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_2.Add(self.static_line_3, 0, wx.BOTTOM|wx.EXPAND, 10)
        sizer_5.Add(self.button_3, 0, wx.LEFT|wx.ADJUST_MINSIZE, 5)
        sizer_5.Add(self.button_4, 0, wx.LEFT|wx.ADJUST_MINSIZE, 5)
        sizer_5.Add(self.button_5, 0, wx.LEFT|wx.ADJUST_MINSIZE, 5)
        sizer_2.Add(sizer_5, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class CarritoFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = CarritoFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
