#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.4 on Wed Apr 10 08:28:06 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class InformeListaFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: InformeListaFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_titulo = wx.StaticText(self.panel_1, -1, u"TÍTULO")
        self.panel_2 = wx.Panel(self, -1)
        self.list_titulo = wx.ListCtrl(self.panel_2, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: InformeListaFrame.__set_properties
        self.SetTitle("frame_2")
        self.label_titulo.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.list_titulo.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: InformeListaFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.label_titulo, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 7)
        self.panel_1.SetSizer(sizer_1)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.list_titulo, 1, wx.ALL | wx.EXPAND, 10)
        self.panel_2.SetSizer(sizer_2)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class InformeListaFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = InformeListaFrame(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
